import {
  ArrowUpRight,
  Crown,
  DollarSign,
  Gift,
  Globe,
  Package,
  ShoppingCart,
  TrendingUp,
  Users,
} from 'lucide-react';

export const metrics = [
  {
    label: 'Total Users',
    value: '12,540',
    icon: Users,
    color: 'text-primary',
    change: '+342',
  },
  {
    label: 'Total Creators',
    value: '1,840',
    icon: Crown,
    color: 'text-accent',
    change: '+89',
  },
  {
    label: 'Total Campaigns',
    value: '2,300',
    icon: Gift,
    color: 'text-secondary',
    change: '+156',
  },
  {
    label: 'Total Gifts',
    value: '$240,000',
    icon: DollarSign,
    color: 'text-primary',
    change: '+$12,400',
  },
  {
    label: 'Platform Revenue',
    value: '$18,300',
    icon: TrendingUp,
    color: 'text-secondary',
    change: '+$1,200',
  },
  {
    label: 'Total Withdrawals',
    value: '$198,000',
    icon: ArrowUpRight,
    color: 'text-destructive',
    change: '+$8,900',
  },
  {
    label: 'Active Vendors',
    value: '48',
    icon: ShoppingCart,
    color: 'text-accent',
    change: '+5',
  },
  {
    label: 'Integrations',
    value: '12',
    icon: Globe,
    color: 'text-primary',
    change: '+2',
  },
];

export const revenueData = [
  {month: 'Jan', revenue: 4500},
  {month: 'Feb', revenue: 5200},
  {month: 'Mar', revenue: 4800},
  {month: 'Apr', revenue: 6100},
  {month: 'May', revenue: 5900},
  {month: 'Jun', revenue: 7200},
  {month: 'Jul', revenue: 6800},
  {month: 'Aug', revenue: 7500},
  {month: 'Sep', revenue: 8100},
  {month: 'Oct', revenue: 8400},
  {month: 'Nov', revenue: 9200},
  {month: 'Dec', revenue: 9800},
];

export const recentActivity = [
  {
    id: 1,
    text: "John created a campaign 'Birthday Gift for Sarah'",
    time: '2 min ago',
    icon: Gift,
  },
  {
    id: 2,
    text: 'Sarah received $25 gift from Anonymous',
    time: '5 min ago',
    icon: DollarSign,
  },
  {
    id: 3,
    text: 'Vendor "CakeWorld" added 3 new products',
    time: '12 min ago',
    icon: Package,
  },
  {
    id: 4,
    text: "Platform owner 'CommunityApp' integrated widget",
    time: '25 min ago',
    icon: Globe,
  },
  {
    id: 5,
    text: 'Withdrawal request of $420 from user destiny',
    time: '30 min ago',
    icon: ArrowUpRight,
  },
  {
    id: 6,
    text: "New user 'alex_dev' registered",
    time: '45 min ago',
    icon: Users,
  },
];

export const mockUsers = [
  {
    id: 'U001',
    name: 'Destiny O.',
    username: 'destiny',
    email: 'destiny@email.com',
    role: 'creator',
    balance: 48,
    received: 320,
    sent: 430,
    status: 'active',
    created: '2026-01-15',
  },
  {
    id: 'U002',
    name: 'Sarah M.',
    username: 'sarah',
    email: 'sarah@email.com',
    role: 'user',
    balance: 0,
    received: 50,
    sent: 200,
    status: 'active',
    created: '2026-02-01',
  },
  {
    id: 'U003',
    name: 'John D.',
    username: 'john',
    email: 'john@email.com',
    role: 'creator',
    balance: 120,
    received: 500,
    sent: 100,
    status: 'active',
    created: '2025-12-10',
  },
  {
    id: 'U004',
    name: 'Mike R.',
    username: 'mike',
    email: 'mike@email.com',
    role: 'user',
    balance: 0,
    received: 0,
    sent: 75,
    status: 'suspended',
    created: '2026-01-20',
  },
  {
    id: 'U005',
    name: 'Lisa K.',
    username: 'lisa',
    email: 'lisa@email.com',
    role: 'creator',
    balance: 200,
    received: 1200,
    sent: 50,
    status: 'active',
    created: '2025-11-05',
  },
];

export const mockCampaigns = [
  {
    id: 'C001',
    title: 'Birthday Gift for Sarah 🎂',
    creator: 'John D.',
    category: 'Appreciation',
    goal: 500,
    raised: 340,
    contributors: 12,
    status: 'active',
    created: '2026-03-01',
    featured: true,
  },
  {
    id: 'C002',
    title: 'Team Appreciation Fund',
    creator: 'Destiny O.',
    category: 'Appreciation',
    goal: 200,
    raised: 200,
    contributors: 8,
    status: 'completed',
    created: '2026-02-15',
    featured: false,
  },
  {
    id: 'C003',
    title: 'Gaming Setup for Alex',
    creator: 'Lisa K.',
    category: 'Hobby & Interest',
    goal: 1000,
    raised: 450,
    contributors: 22,
    status: 'active',
    created: '2026-03-05',
    featured: false,
  },
  {
    id: 'C004',
    title: 'Get Well Soon for Mom',
    creator: 'Sarah M.',
    category: 'Support & Care',
    goal: 300,
    raised: 150,
    contributors: 6,
    status: 'paused',
    created: '2026-03-08',
    featured: false,
  },
];

export const mockGifts = [
  {
    id: 'G001',
    sender: 'John D.',
    recipient: 'Sarah M.',
    campaign: 'Birthday Gift',
    type: 'Money',
    amount: 50,
    fee: 1,
    status: 'delivered',
    date: '2026-03-10',
  },
  {
    id: 'G002',
    sender: 'Anonymous',
    recipient: 'Destiny O.',
    campaign: null,
    type: 'Money',
    amount: 25,
    fee: 0.5,
    status: 'delivered',
    date: '2026-03-10',
  },
  {
    id: 'G003',
    sender: 'Mary K.',
    recipient: 'Sarah M.',
    campaign: 'Birthday Gift',
    type: 'Vendor Gift',
    amount: 30,
    fee: 0.6,
    status: 'pending',
    date: '2026-03-09',
  },
  {
    id: 'G004',
    sender: 'Lisa K.',
    recipient: 'John D.',
    campaign: null,
    type: 'Gift Card',
    amount: 20,
    fee: 0.4,
    status: 'claimed',
    date: '2026-03-08',
  },
];

export const mockTransactions = [
  {
    id: 'T001',
    type: 'Gift',
    sender: 'John D.',
    recipient: 'Sarah M.',
    amount: 50,
    fee: 1,
    provider: 'Paystack',
    status: 'completed',
    date: '2026-03-10',
  },
  {
    id: 'T002',
    type: 'Campaign',
    sender: 'Anonymous',
    recipient: 'Birthday Fund',
    amount: 25,
    fee: 0.5,
    provider: 'Stripe',
    status: 'completed',
    date: '2026-03-10',
  },
  {
    id: 'T003',
    type: 'Withdrawal',
    sender: 'Destiny O.',
    recipient: 'First Bank',
    amount: 48,
    fee: 0,
    provider: 'Paystack',
    status: 'completed',
    date: '2026-03-09',
  },
  {
    id: 'T004',
    type: 'Vendor Gift',
    sender: 'Mary K.',
    recipient: 'CakeWorld',
    amount: 30,
    fee: 0.6,
    provider: 'Stripe',
    status: 'pending',
    date: '2026-03-09',
  },
  {
    id: 'T005',
    type: 'Refund',
    sender: 'System',
    recipient: 'Mike R.',
    amount: 15,
    fee: 0,
    provider: 'Paystack',
    status: 'completed',
    date: '2026-03-08',
  },
];

export const mockWallets = [
  {
    user: 'Destiny O.',
    balance: 48,
    pending: 0,
    earned: 320,
    withdrawn: 272,
    status: 'active',
  },
  {
    user: 'John D.',
    balance: 120,
    pending: 25,
    earned: 500,
    withdrawn: 355,
    status: 'active',
  },
  {
    user: 'Lisa K.',
    balance: 200,
    pending: 50,
    earned: 1200,
    withdrawn: 950,
    status: 'restricted',
  },
  {
    user: 'Sarah M.',
    balance: 0,
    pending: 0,
    earned: 50,
    withdrawn: 50,
    status: 'active',
  },
];

export const mockWithdrawals = [
  {
    id: 'W001',
    user: 'Destiny O.',
    amount: 48,
    bank: 'First Bank ••1234',
    status: 'pending',
    date: '2026-03-10',
  },
  {
    id: 'W002',
    user: 'John D.',
    amount: 100,
    bank: 'GTBank ••5678',
    status: 'approved',
    date: '2026-03-09',
  },
  {
    id: 'W003',
    user: 'Lisa K.',
    amount: 200,
    bank: 'Access Bank ••9012',
    status: 'paid',
    date: '2026-03-08',
  },
  {
    id: 'W004',
    user: 'Mike R.',
    amount: 50,
    bank: 'UBA ••3456',
    status: 'rejected',
    date: '2026-03-07',
  },
];

export const mockVendors = [
  {
    name: 'Sweet Delights',
    email: 'info@sweetdelights.com',
    products: 5,
    orders: 142,
    revenue: 3550,
    status: 'active',
    joined: '2026-01-10',
  },
  {
    name: 'Relax Spa',
    email: 'hello@relaxspa.com',
    products: 3,
    orders: 89,
    revenue: 4450,
    status: 'active',
    joined: '2026-01-15',
  },
  {
    name: 'GameVault',
    email: 'contact@gamevault.com',
    products: 8,
    orders: 234,
    revenue: 7020,
    status: 'active',
    joined: '2025-12-20',
  },
  {
    name: 'BloomBox',
    email: 'support@bloombox.com',
    products: 2,
    orders: 67,
    revenue: 3015,
    status: 'suspended',
    joined: '2026-02-01',
  },
];

export const mockGiftCodes = [
  {
    code: 'SPA-4821',
    vendor: 'Relax Spa',
    product: 'Spa Gift Card',
    status: 'active',
    redeemedBy: null,
    redeemedDate: null,
  },
  {
    code: 'SPA-9173',
    vendor: 'Relax Spa',
    product: 'Deluxe Massage',
    status: 'redeemed',
    redeemedBy: 'Sarah M.',
    redeemedDate: '2026-03-07',
  },
  {
    code: 'CAKE-2634',
    vendor: 'Sweet Delights',
    product: 'Cake Gift Card',
    status: 'expired',
    redeemedBy: null,
    redeemedDate: null,
  },
  {
    code: 'GAME-5512',
    vendor: 'GameVault',
    product: 'Gaming Credit',
    status: 'active',
    redeemedBy: null,
    redeemedDate: null,
  },
];

export const mockPartners = [
  {
    id: 'P001',
    name: 'CommunityApp',
    email: 'admin@communityapp.com',
    owner: 'Alex Tech Inc.',
    users: 5200,
    gifts: 1240,
    revenue: 12400,
    share: 248,
    status: 'active',
    joined: '2025-10-15',
  },
  {
    id: 'P002',
    name: 'ForumPlatform',
    email: 'contact@forumplatform.org',
    owner: 'Forum Corp.',
    users: 3100,
    gifts: 820,
    revenue: 8200,
    share: 164,
    status: 'active',
    joined: '2025-11-20',
  },
  {
    id: 'P003',
    name: 'CreatorHub',
    email: 'hello@creatorhub.io',
    owner: 'Hub Studios',
    users: 1800,
    gifts: 450,
    revenue: 4500,
    share: 90,
    status: 'pending',
    joined: '2026-01-05',
  },
  {
    id: 'P004',
    name: 'GamerGuild',
    email: 'support@gamerguild.net',
    owner: 'LevelUp Media',
    users: 8500,
    gifts: 2100,
    revenue: 21000,
    share: 420,
    status: 'suspended',
    joined: '2025-08-12',
  },
];

export const mockSubscriptions = [
  {
    user: 'Destiny O.',
    plan: 'Pro',
    price: '$8/mo',
    started: '2026-02-01',
    status: 'active',
  },
  {
    user: 'Lisa K.',
    plan: 'Pro',
    price: '$79/yr',
    started: '2026-01-15',
    status: 'active',
  },
  {
    user: 'John D.',
    plan: 'Free',
    price: '$0',
    started: '2025-12-10',
    status: 'active',
  },
];

export const mockModerationQueue = [
  {
    id: 'M001',
    type: 'Reported Campaign',
    item: 'Suspicious Fundraiser',
    reporter: 'Sarah M.',
    reason: 'Possible fraud',
    date: '2026-03-10',
  },
  {
    id: 'M002',
    type: 'Fraud Transaction',
    item: 'Gift G099 — $500',
    reporter: 'System',
    reason: 'Unusual amount',
    date: '2026-03-09',
  },
  {
    id: 'M003',
    type: 'Fake User',
    item: '@spammer_bot',
    reporter: 'John D.',
    reason: 'Spam activity',
    date: '2026-03-08',
  },
];

export const mockLogs = [
  {
    id: 1,
    admin: 'Super Admin',
    action: 'Approved withdrawal W002 for John D.',
    date: '2026-03-10 14:22',
  },
  {
    id: 2,
    admin: 'Finance Admin',
    action: 'Rejected withdrawal W004 for Mike R.',
    date: '2026-03-10 13:15',
  },
  {
    id: 3,
    admin: 'Support Admin',
    action: 'Suspended user Mike R.',
    date: '2026-03-09 16:30',
  },
  {
    id: 4,
    admin: 'Super Admin',
    action: 'Edited campaign C003',
    date: '2026-03-09 11:00',
  },
  {
    id: 5,
    admin: 'Moderation Admin',
    action: 'Flagged transaction T004 for review',
    date: '2026-03-08 09:45',
  },
];

export type Admin = {
  id: string;
  name: string;
  email: string;
  role: string;
  permissions: string;
  lastLogin: string;
  status: 'active' | 'suspended';
};

export const mockAdmins: Admin[] = [
  {
    id: 'ADM001',
    name: 'Admin User',
    email: 'admin@gifthance.com',
    role: 'Super Admin',
    permissions: 'Full Access',
    lastLogin: '2026-03-10 14:30',
    status: 'active',
  },
  {
    id: 'ADM002',
    name: 'Finance Team',
    email: 'finance@gifthance.com',
    role: 'Finance Admin',
    permissions: 'Transactions, Wallets, Withdrawals',
    lastLogin: '2026-03-10 13:00',
    status: 'active',
  },
  {
    id: 'ADM003',
    name: 'Support Agent',
    email: 'support@gifthance.com',
    role: 'Support Admin',
    permissions: 'Users, Campaigns, Gifts',
    lastLogin: '2026-03-09 16:00',
    status: 'active',
  },
  {
    id: 'ADM004',
    name: 'Mod Team',
    email: 'mod@gifthance.com',
    role: 'Moderation Admin',
    permissions: 'Moderation, Reports',
    lastLogin: '2026-03-08 10:15',
    status: 'active',
  },
];
